config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root :to  => 'tweets#index'
  resources :tweets
  resources :users, only: [:show]
  resources :tweets do
    resources :comments, only: [:create]
  end
  post   '/like/:tweet_id' => 'likes#like',   as: 'like'
  delete '/like/:tweet_id' => 'likes#unlike', as: 'unlike'
 
  #get     '/tweets', to: 'tweets#index'
  #post    '/tweets', to: 'tweets#create'
  #delete  '/tweets/:id', to: 'tweets#destroy'
  #get     'users/:id', to: 'users#show'
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(tweet_id: @tweet.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(tweet_id: @tweet.id)
    like.destroy
  end

  private

  def set_variables
    @tweet = Tweet.find(params[:tweet_id])
    @id_name = "#like-link-#{@tweet.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= tweet.id %>">
  <% if current_user.likes.find_by(tweet_id: tweet.id) %>
    <%= link_to unlike_path(tweet.id), method: :delete, remote: true do %>
        <div class = "iine_button">❤️<%= tweet.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(tweet.id), method: :post, remote: true do %>
        <div class = "iine_button">♡️<%= tweet.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", tweet: @tweet)) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", tweet: @tweet)) %>');